# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7af554ac6567ccdd1fe2a75c3164a0db6e66a66e79620ef364fbb16362a3243712f4797d0187e2a219d5531cd2f65374f927a98bab8d14018be24b96848f272

test:
  secret_key_base: 9e12080518b707838e62aa0978c1ac8fcfa90bae242bcdfb89e1f41cfa74cb9a330249e275548be4e4798848dc6f26737a55330ce67ba99f42c63faf5f46af01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
